
# Documentation: https://github.com/Homebrew/homebrew-bundle

# For all your shelly swimmings
brew "fish"

# Basic dev toolkit
brew "cloc"
brew "git"
brew "hub"
brew "vim"

tap "tldr-pages/tldr"
brew "tldr"

# iOS dev tools
brew "carthage"
brew "liftoff"
