
# Documentation: https://github.com/Homebrew/homebrew-bundle

# For all your shelly swimmings
brew "fish"

# Basic dev toolkit
brew "cloc"
brew "git"
brew "hub"
brew "vim"

tap "tldr-pages/tldr"
brew "tldr"

# Apps 
# Note: You'll need to `brew linkapps` when you're done
#       This should be done by the install script though.
brew "macvim"

# iOS dev tools
brew "carthage"
brew "liftoff"

